backend:
  name: github
  repo: aliomershah/ak-products
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "products"
    label: "Products"
    folder: "products"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Product Name", name: "title", widget: "string" }

      - { label: "Price (PKR)", name: "price", widget: "string" }

      - label: "Category"
        name: "category"
        widget: "select"
        options:
          - "Phone Cases"
          - "Home Use"
          - "Clothing"
          - "Lifestyle"
          - "Electronics"
          - "Beauty"

      - { label: "Product Image", name: "image", widget: "image" }

      - { label: "Description", name: "body", widget: "markdown" }
